### PR TITLE
Optimize assets.

### PR DESCRIPTION
**Pull request by RDKRACZ**
Lossless compression.

I remember you said you don't keep up-to-date code online, only locally but the latest update was a few days ago so I thought maybe this is still current. I can do this for a Gobber too if you want or explain how I compressed these / what tool I used.

### CODE REVIEW

**Comment by kwpugh** [comment]
so what is the value of doing this?

**Comment by RDKRACZ** [comment]
The jar file will be smaller and maybe (I don't know how mod loaders work but this seems logical) the game will load faster. Nothing life-changing but still nice.

**Comment by kwpugh** [comment]
Can you just post a zip file with all the new files?  Also, what tool/process did you use to compress them?

**Comment by RDKRACZ** [comment]
>Can you just post a zip file with all the new files?

Sure, gimme a minute.

>what tool/process did you use to compress them?

I used [oxipng](https://github.com/shssoichiro/oxipng) - `oxipng -o max -s full -r --fix -t 8 -Z`

**Comment by RDKRACZ** [comment]
Here is the `assets` folder, btw you can use imgbot.net for automated prs with optimized images. It's not that good as doing it "manually" but still worth using and it doesn't require any help/attention other than merging the pr.
https://www.mediafire.com/file/72wuhd5uyu03zyy/assets.zip/file or https://a.pomf.cat/dpehfg.zip

**Pull request closed without merging**
